### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LuxyFN** [Luxyy-hub/SSL-bypass#2]
Hi luxy, sorry if i disturb you, i wanted to ask if you can help me with the dev.. if you have time..

**Comment by Luxyy-hub** [comment]
I'm sorry but as you can see I don't even have time to respond

**Comment by Mr-Cuda** [comment]
da shit ab this ☠

**Comment by Mr-Cuda** [comment]
this is the best bypass I've ever seen
only 4 string of code 
big D for u

**Comment by Luxyy-hub** [comment]
ol sad

**Comment by Mr-Cuda** [comment]
WOOOOOOOOOOOOOOOOO live chat
it will not happen again

**Comment by Luxyy-hub** [comment]
fastest way

**Comment by Mr-Cuda** [comment]
dropbox

**Comment by Mr-Cuda** [comment]
yo can u help me with this?
i wanna make custom playlists for the lobbybot

{
    "name": "Playlist",
    "version": "21.50",
    "manifest_version": 2,
    "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAHcA1AMBEQACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAADBAIFBgEHAAj/xABFEAABAwMBBQUGAgcFBwUAAAABAgMEAAURIQYSMUFRBxMiYXEUMlKBkaFC0SMzU2JyosEVJUOx4RY0gpKywvAIJDZ0k//EABsBAAEFAQEAAAAAAAAAAAAAAAMAAQIEBQYH/8QANhEAAQMCBAQDBwQCAgMAAAAAAQACAwQRBRIhMRNBUWEUInEGMoGRobHhI0LB8FLRQ1MVFjP/2gAMAwEAAhEDEQA/ANW7FUjVHiT06Vuh4K4mSlc3VuqXBIVpoanuqwJBTbMr8LumPxChOj6K5FVcnplaEuIwdU+VDvYq25rXix1SD7CmuHiSftR2vus6WAxnqEWNIwAhZ05HpUXs5hFgqLeVyLJYDqd5Pvj71FrrFHnhDxcbpeK93TmFA7p4ipvbcKpBLw3WOyauEbCUuJ8QKcpI5j/ShRPubK3Vw+XMESxKDzjkNeMOp8JPXiD/AOdaapFgH9FPDHhzjCeahPur9vjrQljvHknQK5D/AErka/2XFXWeIYQGO39eenf7rp8GrYDKKSqflOwPXtdUc5iz7bMpj3BHcTWfEytKsepSeNY1TR1OCPzwuu0rpq3DnQi+7fsqRXZg0t0qkXGVJ/dW+SMVE+0kpGyzfDRrabPWWNakISyyhCUJwN3QCsKprHTkl2qNoG2C5cb8xAkKJjuvtHwrU3jHTAzxolNRyFocTZW4qJ8rd7Hun7PDtqiZMYJ3jqGyMKAPDI6UWSN8bM0hvyA/2qc/EYcrh8UqXlvvuv4UVvObrSOGg0T9cZ+deiYDSGnom59zqf4+i5TFqoSyBjB7ug7k/wB+iTW0VyC2FbxHvL5E8/lW+HeW65tzC+QtGvdOJCWm+gHE0K5JWg1rY22SUh8unA0SOAorW5VnzTZzYbLseOXMFWietJz7bJ4YC/U7J5KQkYGgFC3Wi1oaLDRAelBGUo8SutSay+6ry1LW6N3SS1qWd5WpooAGyoOe52rl1tC3D4BmkSBuk1jnbJtqIlPiWcnpyobn9FdjpQNXpgAAYGgod1bAA2XyVJUMpUD6U9rKLXNcLgqDrCHBqNeopw4hRkia/fdJuxlt6p8SRzojX3VCSnc3bUKLLymjhJ06U5aCoxTOj2TrTyHh5/CaEWlq0GSskFvol5EUjxNDTmByqbX30KrTU3NqlDkAKDby8IOgV8NNI02uE1PPlOV+32RJ8RSVk4woakDmOoqMcgIRqqmPvDf7pqyOolNqt7xwo+JlR5K5ihVDSw8RvxR8OlErfDv+CReQ7bpwVqlbagfvRgRKz1VKRjqWcHorTaeOlaGpzOqHRqR1IqvSPsTGVpYtEHsbUM2K8rkNuN7RIS3KaabS/vJWTrgHJQOWeXpXP4s85JGZS4ar0Kkxp1Rh0Ub/AHi0X7mw1+K3EebnKt8nTNcE+G2iGBdPR1O3RwNhRZjfiVnxL8vIVbo6Fhdd5ujOYIG3dqfsj3CzH2GQgKKkKwUJ5Ix0rWqactbcck1PVjiN0VDZIi999TK1IcAIJB46YqgxvEIza2WjXSNyAOGi0LqDBhJdUCJL6dxlPNtPNXrXpjfO/KPdG/crymX9GLOfedo3t1KVZaDCNcZPE0ZxuUCKMRN1QZ+8lQQvRfwfD6+flyqURB1Cr1TjfKd+n+18xF/E7qPhFO5/RPDTfuemFuIbT4lAeVDAJVp72sGpST0hbg3fdT0ooYAqElQ5+g2QkJKzgAk1ImyC1pdsm24gGruvkKG6TorkdLbV6ZAAGAMDyodyVbaA0aLilpSMkgClYlM5waNUEy2wdAT51PhlANWxJJUU6pJHpRiAd1nhxbqCmG5ah74yOtDMY5K0yrI0cmm3m3fdPyNDLSFbZK1+xUHY6F6jIV1FOHkKElOx+2hSjjLjJyeHxCihwcqT4nxm6YivqcUEKxvcj1ob2gaqzTzlxyuUpMYLJKRur5gjiaTX2UpqYO1boUza5Lbn93zyUpzhlzm2emelCmjIPEj+KLRVAv4eb4Hp+EG5wX7fIDifCQrKVDn5ipRStlbZQq6SSnfnareYwm+WpEtgD2hI8QHMjiKqxvNPJldstKaJuIUwlZ7w/hVsi6IY2NkIWjvJCT3DDZ4qWr3fpn7UOtkFM8y8t0TCmiqpeA/loV5htBszLbfiuIdU4jdW47vgYbcwPrk5rnabHWyRyMIGp+a6M0YFsugVLB2iutlfKHW/aIyTqkuZIHkT/WoTUdNVDMzylSa+SPRy1Vo2oguOByJLcabWPxDVB/eT09KzXUcsR8w16hdBT1DKuMBwGZaBe2ciA1/eMRT0dXuyY530EfLUfMUZolLbBwPYoUlFEDdpIPoibK3WPdZE9y1BTo7o4GN0JV5k6DTNNSUUvGs5qhiD2sgaXHZaCQtc+4KeCFKKsJaR0Ty+vGu8YBEy3zXmryaibPb09ESUE2tKUDDk9fuJGoaHX1qLLzHo37qU5FKAN5Dt27quZY3CXHVb7nEk61Zc4bN2VKKDIczjcrsh5TSAoJ973Srn6UzAHGylNMWDTmkSVOr6k/ajaNWf5pD1KZaic3T8hUDJ0VqOl5vTSUhCcJGBQiblXGtDRohuPto0KsnoKcMJQnzxsSzktw6IAT58aIIwqr6px90ICiVHKiTRB2VYuLjcrlJMrJbDa+KR6igBxC1nQsdyS64Z/ArPkamJOqqupD+0oC2nEe8k+tTBBVd0T27hTbkLRp7w86iWAqbKh7dEy3JbWNTuHmDQywjZW2VDHix0XHYqHMqT4T15GnDyN00lMx+oTMWYkYYuiCpHBD6feT6nmKG6M+9H8kaGpyeSpGnXmPVHnWdRaDqCHmiMpcRrUI6gXsdCrFRQZm5m6jkQixbvGaguR74rCW05S4QTkD75oE7Qx3EYVZoXumjNPML22PX8qrhXV+KHl2lIMd7VsykEH1xxHzrncS9oorhjG3I3K06DCHU7nHP5TyVS4/cjJU8+mM4sqKvCnGDXPVeIOrBaRxWxDTQw3yNsSqu93CX7OveYTw4A0KmhjzDVGcbLziS8ZEspUnBJ4V0jW5GaKoTc6quuMN1h0uNAj0qzFK1wsUNzSw3CCzcrpH/VSn0HyXRjDAT5mgoza2qaLB5Wq2Z2+vtpiLhJYiSGnDkqcSpK/wDmB/pUojHTm7QqtVxKxtpHLUwe066wGQVWyCp1RIKvEBjkM5ozarjmyrMo2QDy7q62c2lN633JURbMkq/SZVvDXgR5U1RjMNKQ2VpDeoWeMIkeS9rruPVaiS9Ghtp9nSqTIWMhS04Qj5czVuirIq8F0TxYb23VStYaKzC27z12/Krww484p2UtRUrUknU1pFwaLM2WWKd8pzynUo43Gk8UpFQ1KsgMjCC5LQP1eVHqakIygPq2jRuqWcfWvirA6CiBoCqPme/cqCElRwhJPoKe4Qw0nYIyIrivewn141EvAR20sh7IyIaBqpSlVAyFWG0rBubowabAwEJ+lQuUYQsHJKJmOD3kg+fCjGMclTbVvG+qKmWg+8CPPjUMhRm1bDuEVLza/dWD5ZqJaQjtlY/Yri2G16lOvUU4cQouhY/kqHay4/7N2dd0DPfhC0o7snd4nHHBppJ8jb2UYcO4smUOt8Fk4/au27hpnZ14yFcEsyc73/Dun7VS8W6+2i12YUA33rHtt8jf6L5XaytKT3mzzuAkKVl4gAHgfd4Gn8X2Uv8AxtxZzvoor7Wp7CmfYrXLjRQSp5sPZ7xX4cHc8IzyHHT0NNz5ZJC6Qi3IAfc81cpaWOnblbf+PgFFfae2t9tUzZ6W6snKEKlEBR9N3WqtZDNPGWsflPW11bY4MNwEST2tHdyvZ55sHTKn8f8AbXPD2ade5l+n5VrxfZIyO01QAUuyOtg8Cp7Gf5aM32fI/wCT6flLxfZJytupD7HeGzvBhQzv753SM4znd61YZgmX9/0/KXi+ypHdomQ9ly3LSoHUFzBH2q4KBwFs/wBEMz3N7I82+kIPf2h9pOd3K1Ea4zjh01pm4e5p9/6JzUAjZVguAfJLUF1QB13Tn+lHFM4fuQ+KOimm7Bgby4LgAOMqONenCmdSE/uTiUDkrOFtRHUgtO2d2UjmlDuMfRNANBI1wcySx9PypGoBFiExA2wkQrgh2Pa3y00f1SlEqKTyJ3fv5Uaro/Ew8NztUKOQxuuFp2e10qb02cecHDIf5/8AJWRS4HPSzCaGaxHbl03U5pGTMyPbooDtfaRkO2B3PIe1BP8A2f5V13iT0WMMObzcrbZLbBW10uS0i3ezdwgK0c3uJx0+5NW6ecPuLLIrsPfHYg3utWiGo++oD0o5kCptpDzNkdEZtOpTnzJqBeSrDaaNvdFAAGgwKijgALiloTxWkH1pWKi6Ro3KEqW0OZJ8qnkKEaqMbKBmp+A/Wn4aF4wf4rhhDkv60hIkaMcioGGscCDUuIEM0j+RUFRnU8UZ9KfMEM08g5Lg75v400vKU36rOoWW7UXXF7GSAtaT+ma05+90qrVgCNauFSvdUAOKf2Bsidleyy4bTsIR/bEiE5JbfWkEtoAO4kZ5aZ881lrplm7VtU7eeyS+xZndmfbEsIbfCAFKa3xuAnngg/akkvStr5jw7JnLqO7EwRI8jvNwfrN5Cs49aSS802r2zuTzmx08x2WNoobjvfRt0DeCw3uEg8AtKvlr0pJL1Pbmys7Y7Bu+xsbsnuxKijdAUl1Izu+vFJ9aSS86lTn9t7tsBZroUezSWPa5SUtpHerRv8fUII/4jSSV52g3O/7J7Xwbg3DDmyiGER3GkMpU0lBPjCgBkHQEctAOtJJd2P2Yt987UNpL/ISzJiw5CUxUjCkFwpB3vkBp5nypJJnYrG19028tN+QiTD9tSEoUkeDRSAUnkQG0YPLFJJI9h8R+1X3avZ6QoLYgyAUBSB72VJ3uHNKU0klqtmu7ud92xtM+OxIhtTUhLTjQIwtobw9NKSSwfZHHRaO1HaGxxFBUFKV4SoBXuL8Op103iKSS0F82kmWDtUdZDDSrKuIw5cFFsfoE5KQ5nkAVJz5UkkbsNlmfZry2stux2Lm77Od0aJV4uPMZJPzpJIFlskbbbZPaG1T2mu9h3SW3Cf7sbzKt9SknI46q1HMaUkl552OPJg3y6RpR7t8thASfiSo5GeGfyNWaUjPbqs3E7iMPtoF6qqafwo+prS4a541h5BDVJdPPHoKkGBBdUyFDU4tXvLPoTUw0IZe87lRHpSUF0IUeCT9Ka4Ugxx5KXcufAaWYKXCk6Jn21PwH60PhlWxWDouiYj4Vfam4ZT+Lb0UhLb5730pcMp/FxrolMnqPlTZCpeKj6rH9q7rTmxkgIPi75rl+9QKlpEeqvYfJG+oAatY8tK+woFGo/wBnkjTqGQD9wazVvr8yNd93Lwb7zu8Au7ucYyMb3zxx50kl+n9oX2o3Y+3IfYTIZahRVuMq4OJCmyUn1GlJJeNdoElq6doDN2gfpLfIdjJbdSPDncQSjPDIChkUkl692ZbRJk3zajZ95zL0O5PvMJP7JTh3h8lH+YUklhdsGbtZu1y1NWeM28uMhT8NsK3S40StxxBzgDGXEjy3edJJet7LbWWPbK3KctzyHd5GH4jwG+3nkpPTz1FJJVnZvZ4lgnbT2uDoy3cg42j4EraQQPQagelJJUPY7/8ALNu//vo/6naSSa2Ddbe7U9u1NEEBTCcjqAQfuDSSVps+G5N22zjW1aody9tT3kopCxq0ndISdNNf86SS807FokmB2p3aJNc72Syw8l1zOd9W+nKvnxpJLR9pdxhpnbVWcsoFxmWyMYy/xu/pMd0B6nOn9KSSn/6c0La2fvDbqChxE/dUlQwUkIGQaSSu+yM4Z2nJ5XyT/wBVJJeedl0aJc9qNrGZCA5HdWVAA4I/SqIII4EcQRXOe0NVLSiKWI2IJ+yNExr7tcLhblqDItr3s9wKpMc6MTB05JdxwV+9wPka2sH9o464cN5s/wC/osGuwVkZMkY06dE8I7I4I+tdDnKyxTxjkpBpscEJ+lLMVMRMHJSwOlNcqWUdF2mTr6knSPsbnVNH4gWd4R66Ia/iT96biBP4N3Vd9iV8Y+lLiJ/CO6r72I83PtS4iXg+6ynaowhrYqQd3Ku/a8WT8XSqtU4li08MhbHODzVVsDt5an9i5mx20stUJDjLjMaZuFSQhQOiscwSfIj75q6FZaZOslm2R/sWzzVy512LLlyld2QhltOoaSM6kKOSeePokl6TtJt5sdN2BXs7GvK1rUwzH7z2Ved0KSCrGOgJxmkks3dLnsKiNsnZ7bdnv7Pt8xUiW+qOsqJxnJGPxKAGnAHypJKte2qtNi7VxtDYZrkq3SXN+TlpSSlLh/SJ11ONFD5DlSSV9fdutnpXazZL8xMU5bYkZaHnO6UMEocGMEa8R9aSSX2fuGxWzW2UvaiDfXlQywpxm3oYIcK3CoFs8sJwDr1GumqSVfsj2puW7bq5Xi6tLMC6LHfNt6lkDRBHXA0PXOelJJaC17b7N7IP7V3O3zzcZNylJXEYbbKc+DeyongApxQP8NJJVvZDtlZLHIvl02juqm59xeBU2GFKzqVFeQOZUdPLzpJLTbO9oWykDba+Pf2oVQ7oGpCZC2FIS24kFJbPPgAc+eOVJJVFg2t2Kt3aTd72zLdixVxw2hRbWv2p1Sipa+e6BgADnxpJI0naXYO59oydp594d3IbTSYzQjL3VrAVlStM6ZGnWkki9mu3Wyez0S7KnXZaXp1ydkd37OvwJJwnUDXIGfnikkqlXaNabDspd41hkPSLrdZsl7fLW4mOlayAcnid3BHmeVJJVvYcSm6XPBwe4R/1VzPtMLwx+p+yt0m5XtSHTjC9QRjUca4vVrszTYq2QkZdsXjvLc4Ugf4ClYT/AMJ5Hy4eldbhHtU+mtFVDM3rzH+1h1+ECfzRHK76H+9lXu+0NL3XS4g8go4zXodLUwVUYkhNwuPqIqimfkluD91DvHPjV9as5QgcR/Vc7xfNavrSyhLO/qvu8X8SvrSsEs7+qeMlofiz6UHIVomoiHNRMxA4Amn4ZQzVs5KBm9EfepcNQNYeQUDLcPAAUuGFA1b1V7Q2d7ai1LtpcdShS0qKm0A4wc0OaNhbYmyPSVU7ZM7W5uyzjfYozu70i7PNp6BCFK+gNcxjWIxYdE0s8zidtvVdNQmpqHfqNDR63Kq5PZSe/wB23SJExkIUFLSptHduDGAoE6AjXIzwqjTY5G9mao8p5DqtJ9M5psF9Yuy+FNech3C7PMTm0hRS20ChY57pOpwf6VXqseljbxI4wWnrupeG7p6+dklps9tfmv3qVusoKiO5Tr5car03tHPPKI2xjXukKa/NAkdk8eNZE3FyZOUvuQ4plDaSQcZx/rVuDHRLOYiAOh6qJp+hQ7P2UxJ0AyZV3cjqSgOKSltKwkHhrka1Cox98b8rI7qfhdBqs9B2Xsz86X7Rc32bfFSoqkbiSVHOEgep4VourKkRNc2O7jy6KBhaDumdktgmb+y9KemPx4wXutENglfnxqviGMOpCGBoLuadlMHC99Fcy+yyBGU0TdpJbWcFXdJ0P1qjH7QzPB/TF/VT8IOqfY7HbW8nIvUrh+yT+dV3+087T/8AIfMpGltzRVdi9tSMm9Sv/wAU/nUP/aZ/+ofMpvC90q/2R2xoj++ZWpxjuU/nRm+0k5/4x804pB1RWOxy3Okf3xK16Mp/OoO9p5m7xj5pGlA5pO+dlVttr0OK1d5LsmSvAbLSRuo5qPl/rWthOKT4g4jhgBVpWsjF3FMXLsWDTZXa763MWP8ADUEoUfvW9Ix7W3a03VOKpjc4hzhb1QNkrZ/slcX+/W8l51IQtt1ITjBzkda5jFeLUNDZG2stemEepBvdejwbwy+B4wTz1rlJaVzSrVhyVk2+n3kq0561WLORTFSkKalvhDid9psboIP4jxx6aVqU1bPh8Y4TiHFVZaeOcESNBCA7bUAAtoDnkBg/611+Ge1jJrR1Pld1WDV4GweaIfBLGKz8H0JrrmyEi4WG6ljBsRZc9ka8/rUuIVHwsaRShaj4Uk0a4WeGOOwRUxHTqcD1NQLwjNppDvojJhJ/Gs/IVEyIzaMfuKImMyPwAnz1qBeSjNp4xyR2kFxXdtAachy9apVtbBRx8Sd1h9T6BWoIHSuyRhAv9yZs8JWVeLGdOKjXmdRUTYtVGV23IdB/d12FHStp47BeU23bC4QNozJDboiPkNvBbSiAnPvgDmPzrfkwyCSnyOIuPT+6qRkfm1Gi2LEK53qezeLM+WmWXihh9bWRPGBlW6cbiQQoDlgZ1NVmshsKNzbvdyvskXuBJOwRNpZs+4xi89FRItsWSlEoRzvKJSQchPw/eqwooqOcxB1nkaX2+anE++y0k6VFuzzVuZfALiA4UjQ7mcH8qxWwTU15Xt2UmkAEqo2qtglW96DZw82ojVLKwnvDjABzyrQw6ucw/q2yk8xsk5mcamyzUy1d/ZoGzhgLjJYQlyS6MeNzng89edaPiDHM6pEl77endRaGubYhaG2wvYorcdhAS22MJAGKxp5uK8uduUYNtoEeY130ZTbp8JH0PWoROyuuE6zq79MsbqkPJXIYBwlxPED94VpijiqRduhUXOt7y+X2i27GsgAjiCaiMDm6IZlYFG3bRyb7MSIMZ5xkcXQg7v14VKWgZTR+d2vRSa/MNAtxYpLD2EtvJUpKt1SyDuJI4jz40qHApqx2dws1Vqmqjh0cdSnJdkeRJcuEMtzFOABS9N8J6A9PKu6w+GmpI+E1uXv1XOV7aqU52EOb0Vf3zSlFt1O6oaFK01q5SBdp0WPx4ycrxY90KXbYU5rcfZStHLTh6dKHIxkgs8X9VYizRnNC4t9Dp8lk7rsxcbfvP2WQuS2NSws4WPQ8D86wavB4yM0a6ClxYuOWTfqqqyXi/T5RixYjyQg7ri3EFO59edc/UUlNTDPKdei2GyudsF6bCS41FabWgJCRjQ5NcrUPEkhcEWyhekXBy1OC2PqZdPvKR74HVPnWhgzqZtRef4X2QZgSNEFlmVGtrMl0lxt04yo6g/8Agr0+jdm8i5bFQYwJQPVc9tT8Bq/wysbxg6Jr0GB5ChK2hrebR7yxnoKkGkobpmN3KAuYPwJ+aqmI+qrurP8AEIJeddUEBeqjgJ6mneWRtL3bAXVcySSuDAdStBBhCKyEhR3jqtXMmvGcWxZ+IVBkO3IL0OjpmUsLY28vqUb2VnJJQnJ4kjU1lcR3VW8xQ3YDC+LafpU2zPHNLMqW7Xdpph2I02qQ82stKbYISWlYyPTQg1q0sU8UrZ82XmCU+UOBS8HFi2bWt1srkOqKtwOd4rKufAZ+laNPUQ1OIZ5tQPghyNIaGtST0uNDRblyW20TXNAs++lGdQD1OeFWDapfI/8AYBt1KQbkbYKscuUq0TLnDhy1SVtpS6oSTq0lRyUpI4nXnQjTQzxMle3Lfop5iX2Vhau/k4ff4qAISfw+VUahrWCzUS6uwjTIFZxKkUCQCcJ3eNTYkEq5CZeOXWkmitmc3YpHVWNqtEQErDLQKfxbgJqRkfI0lzjYIbiAdkvtHPIei2aKvu3JJ/SqT/hND3j644eZFW8Cw19dUZjsFWqqqOliMryrtqyQDBaRYilktJ3e6UT4v4vPzr0eJ5gAjcPKubqYG1ZM0LvPz7qvalOMPltzfYeToR7tXSwOFxqFmMqHMflf5XJiQ8qUndktokYGiiN1Y9FCoMYGG7TZFlcZR5wHff5qiucuPaGFypDpYYTjxOY48ANOJo5eA3M9UI6eUyhkQNynrcuRPYS7ulDaxlKlJwSPSuKxb2obGeHSjXqf4XWUWDFtnVDrnsrGPFZjI3W0geZ51wUs8krszjcrfGiJ7ygBqBQtgnTTKCOHGotJzaIbiq3bO5xbZaoaJUhtlL8kISFHGVEHhXons/VuyMY83I37LIr4uJC9tuSqiw6DgoVp5V3OYLhuDIOS4t5xfvKOOlMGgJ3TPduVAAk4Gp9KkhgE7I7cRa9VeAedQLwFYZTPdqdFYW+O2mQg4yU5OSK5/wBpKl0eGS99PmtnC6ZgqW25aq43hXkRGq7Gygt0JGaVrqQaqPaDaq32SOp2W+lOOCc6k1fpMOmqXWaEjZouV5f395252kMyysO2xtQDTsoE5dA0AxwUePpzr0HDcIDIMkpzNHXl6LHrsRZAQ1ou87ALdzOzizR7ShiTOnLum5kP97vbqupSdMVosoonnyNsEF9bJEz9Q+boFnTZblGWz7XcJDrqUkNPg4QpIOMpSRgGuexOEUUmTKMp1WnQ1TKuLONOSZjWRxx8LeeW6VHKis5KvWseWtGWwFgFfDbLYQogaZSAOVZUs2YFR5psNaVSzJ0B5sZBxzojXJ18GAqlmTK1YShmGScDmT5VYLx4ew3cUJ2r1ndiW4tyFxuFy/3m5rHdE/4bSfcA6H8XzHSvSMMon0NMwtGu6wqypp6qR1M7lp8Uy8mRapZZdKgBqhwHiOoreaWzNuFzbuJRS8N+3Ip2Q+zcWQianxAeGQjiPUcxQQx0Zuz5K5I6OqbaX4Eb/lU8p02tC1yHEezJBPeZ8OPX+lWMzHNzHSyzw2aKQMAzX2tzSsW2Kvs5i4XRhSYzB34cRzkf2ixzV0HL1Nee49jxkJgpzp16rtsPoOA3M/3j9Oy04SEJA6VxRJJ1Wmo6rOnCnvZOjtNbvKhuddQJSl4vUe0NpSpJflufqYrZG+55+SRzUdBWtheFVNdJaIadeSqVFTHAzNIbBUqIbM99E27BmXOA03k5Qz+62Dw9eJ516lQ4XDQxZGN9T1XLzYiah12usOisqvICTbhn/EUPlRi/oqDKQ/vTKG0oGEgChkk7q2yNrNgvnHEtjKjimAJ2TvkawalATPU26FpQCgcRzNU8Vw3x9G6C9idvUbKNJifAqBJby8/RGk32HFRvPSG0fxqxXlEuF1Mcpiewghd7FLHMwSRuuOqxO0HaGkrMe07iyo7veqJ3QfLGqj5DNbFFgLj5pfkmfMwbFUlus9yvEkOvtODfIK5sxHjx8LLZ93+I6119HhTtL+Vo5f7WDW4zHGMrDmd2Xq1ojMWKKlthtAkAboSBoyOnmeta7gH2a3Ro+qyILwkyv1kd9PyoLDs2UmM2ol504UvjgczRbiNmY8kB5fNIIm+8UfaRMRz2SKylOWFbiFZwSSNR58M/KuaxyMGhfM/cWI+y6ShlayobBFsBqhR4QSE15u+Vb5KsUt4SKA591C6+KRUbpILqNKm0qS60ik4pkaQguW99tPvqbUE+pBokT9geqGd7rPNxVW6FbXG89y9FbUkee6Mj617dTycSPKdwuBxCF1NUZ27HX8K39obuMIR5SsY/VPnig9D5UMsdE/M34hWeIyqiySH0PRUkuWmzpeXPWGmWtXCo6Y6jr/WrBc0szX0WdE2aOXhWueiXgofvb7cyaypmK2rejxVjUkcHHB15gcuPGuAx/HC8mCA6cz1XbYfhzYP1HjzfZaZGEJCedcS7zG61VMIUricVG9kyKAltClKUEoSCVKUcADzNM1rnusBcqJICqZV1flo7uyhAQsf786MoH8CeKz56J8zwrr8J9lpJrSVWjenMrKq8RZFdrNSqpu2+yLcdUVvPukF2Q4reW4fM9PIaDkBXo1NDDAwRxNsFxtY+omfnkN/4UuFWVRUw86BgLOKjlCIJZBpdWS1JQMqUAKButVzg3UlKOy+TY+Zogj6qnLVcmJZSio5USTzNFsqZJJuUdmKpfic8KfvUHPtorEVMXau2TLkeO613brLS2hxS4kKH3oJ8260GWjHl0VYmNAiu78GDFYVjBW2ylKj6EDhRI4mt1sqdRVvf5QdE3CQor3xoBwJ458qd5FlCmjJdmTD7oZbySM40HnQ2turcsgjboiwVmJHLgP8A7mSMhXNtHX1PL61CQB7rch909KeE3N+9w+Q/Kg1FTJujLqk6R21EHopWn+QVXHe2FXkiZTg6nX4LocFjsXP+CuEtgCvOyVvEqZFMUygRTqSC5UgnXzdIpFMJPSmabFQKSIaeZethKQWzlj9xXEDyBr1/CattRSx1DOlnfDdcpWwkl0EnPVpWfenNWpK3JryWWkqwveOMHy8625XNDM5NgsGmEol4YF+yVDZ2jksSZDeYkZWYyF9fiP8AQcq8/wAcxlznGKLRq7jDqHhDO/3v4Wmjtbid1AHqa4x77m5WqmG0Y5ZND3TEqvmX6KwssRELnSRxbjjKUfxK4CtahwSqq3Cw0VKorYoRqqSaiRdXG3LuoFttW8iG2f0QPVQ/GfXTyr0XB8AgoW5nau+y5GvxqaYljNB9VZMygcJcAAGmRwrcdH0VKOrvo9NJIxoQRQ1aBB2Q3I6HNToeoqQcQhPgY5LmGvPhUkjzqfECqupH30SS5rbhyp3J6YP5VIZQhP4jzdy4mQyTjfGT5GnzBRETjoAnGVRm8Fx0KX/CdPtQXSXV+KlDdXalHMyMBku6D90/lUL3Vmxskn7ky6cBzCfQ6/ajNAG6zppHSaAaKLDrLqtXAEjjofyp3PACjFTukPZP+1x0IP6QbqeiT+VBvcrSy5G9lXOzmXHN5SxjkMH8qMLALMkLnvuU+3LZAKnHQVrOVHdP04UEkXsFoxsc0Encq2iPxWmx+kBUdScH8q8lx+d9XXyOA0Gg+H5uuuoYhDCG890b2yP+0/lP5Vi8J3RXLhcMyP8AtP5T+VPwndErhRMyPj9Z/KfypcJ/RSuEJcuP+0/lNSETuie4UUTI/wC0/lP5U5id0T3CMmbHx+t/lP5VERPvt/fmolZHalg3m4RZlnuDsJ2LlL7ycjvG+OMc8HPGukwmulw6Nzd823ZClpo5QOIpNRIlxcaF27mYoq1W62TnzwR0odVX1chzZz21U2QQsBytAurZm3221uodteGGcFLsdCTuKzwUByI8uINUZKiWpZkmFzyKcEXQ3doovtCYzOXX1AkIwUgDzOKPQ4LPVvyjQIVRVMgbc6qtmy1TSUTJau6B/UsgoSfU4ya7rD/Ziiphmk87lyVZjdVIcsYyj5p+DKhNshlndaSn8CEED/Kt7I2MWaNFVildL726I67Fd4uYVyO6fyqTX2SkpxINkg480hW6Vg+eDRg4FZz4XsNiutT0N+64AOmD+VI5SkwyM2TjNziuaFZSr0NCcLK/FJn0sje2MftfsfyqF0bKV//Z",
    "description": "bb Playlist wow",
    "ids": {
        "id": "EFortGameType::BR",
        "gamelaytags": "Athena.Playlist.Creative.TDM",
    },
    "content_scripts": [{
        "playlists": [
            "https://fortnite-api.com/v1/playlists"
        ],
        "js": [
            "content.js"
        ]
    }]
}

**Comment by Luxyy-hub** [comment]
u should put a link instead of this shit 
and idk send me the content js

**Comment by Luxyy-hub** [comment]
and don't put manifest_version 2

**Comment by Luxyy-hub** [comment]
BROOOOO 
WTF
I SEARCHED THE IMAGE ON GOOGLE

JENNIFER PASSED RIGHT AT THAT MOMENT

SHE SAW ME WITH CESURED T_ITS ON THE SCREEN
THE FUXK

**Comment by Mr-Cuda** [comment]
tt POV

**Comment by Mr-Cuda** [comment]
[gameinfo.txt](https://github.com/Luxyy-hub/SSL-bypass/files/9478706/gameinfo.txt)

**Comment by Mr-Cuda** [comment]
it's .json 

i had trouble sending with the .json

**Comment by Luxyy-hub** [comment]
wtf

**Comment by Mr-Cuda** [comment]
yes

**Comment by Mr-Cuda** [comment]
why not manifest_version 2 ???????????????????????????????????

**Comment by Luxyy-hub** [comment]
Um yeah
do u remember joh?

**Comment by LuxyFN** [comment]
> BROOOOO WTF I SEARCHED THE IMAGE ON GOOGLE
> 
> JENNIFER PASSED RIGHT AT THAT MOMENT
> 
> SHE SAW ME WITH CESURED T_ITS ON THE SCREEN THE FUXK

what?

**Comment by Mr-Cuda** [comment]
live chat ezzzzzzz

**Comment by Mr-Cuda** [comment]
joh the epic shitty?

**Comment by LuxyFN** [comment]
can i drink coca cola?

**Comment by Mr-Cuda** [comment]
yes
